import { browser, delay } from './cdp.mjs';
import { writeFile } from 'node:fs/promises';
const b=await browser();
const checks=[];
const check=(name,passed,detail)=>checks.push({name,passed:!!passed,detail});
await b.viewport(390,844); await b.navigate('http://localhost:3002');
await b.evaluate("scrollTo({top:844,behavior:'instant'})"); await delay(300);
check('Covered hero cannot receive pointer hits',await b.evaluate("![...document.querySelectorAll('.hero-actions a')].some(a=>{const r=a.getBoundingClientRect();return r.bottom>88&&r.top<innerHeight}) && !document.elementFromPoint(100,300).closest('.home-hero')"));
await b.evaluate("document.querySelector('.home-surface a').focus()");
await b.key('Tab',8); await delay(250);
check('Focusing previous hero link reveals it',await b.evaluate("(()=>{const a=document.activeElement,r=a.getBoundingClientRect();return !!a.closest('.hero-actions')&&r.top>=76&&r.bottom<=innerHeight})()"));
await b.viewport(390,740);
check('Viewport height change preserves fixed layer',await b.evaluate("Math.abs(document.querySelector('.hero-backdrop').getBoundingClientRect().top-(parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--header-height'))+12))<1 && document.documentElement.scrollWidth<=innerWidth"));
await b.viewport(320,740); await b.navigate('http://localhost:3002');
await b.evaluate("document.querySelector('.menu-trigger').click()");
await b.evaluate("(()=>{const els=[...document.querySelectorAll('dialog a,dialog button,dialog p')].map(el=>[el,parseFloat(getComputedStyle(el).fontSize)]);for(const [el,size] of els)el.style.fontSize=size*2+'px';})()");
await delay(150);
check('200 percent menu text stays in a scrollable dialog',await b.evaluate("(()=>{const d=document.querySelector('dialog'),r=d.getBoundingClientRect();return r.width<=innerWidth&&r.height<=innerHeight&&d.scrollHeight>d.clientHeight&&document.documentElement.scrollWidth<=innerWidth;})()"));
await b.evaluate("document.querySelector('.menu-contact').focus()");
check('Last menu link accessible with enlarged text',await b.evaluate("(()=>{const r=document.querySelector('.menu-contact').getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight})()"));
await b.shot('docs/screenshots/final/menu-200percent.png');
await b.viewport(1440,900); await delay(200);
check('Desktop resize closes menu and unlocks scroll',await b.evaluate("!document.querySelector('dialog').open && document.body.style.position===''"));
await b.navigate('http://localhost:3002/urunler');
await b.evaluate("document.querySelector('#sakatat').focus()");
await b.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r'});
await b.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13}); await delay(250);
check('Category can be selected with keyboard',await b.evaluate("document.querySelector('#sakatat').getAttribute('aria-pressed')==='true' && document.querySelectorAll('.product-card').length===5"));
await b.evaluate("document.querySelector('#product-search').focus()"); await b.send('Input.insertText',{text:'ciğer'}); await delay(250);
check('Search accepts actual browser typing',await b.evaluate("document.querySelectorAll('.product-card').length===2"));
await b.viewport(844,390); await b.navigate('http://localhost:3002');
check('Landscape opening fits hero actions',await b.evaluate("document.querySelector('.home-hero').getBoundingClientRect().bottom<=innerHeight+1 && [...document.querySelectorAll('.hero-actions a')].every(a=>a.getBoundingClientRect().bottom<=innerHeight)"));
await b.shot('docs/screenshots/final/landscape-refined.png');
await b.viewport(390,844);await b.navigate('http://localhost:3002/urunler');
await b.shot('docs/screenshots/final/catalog-refined-mobile.png');
await b.navigate('http://localhost:3002/hakkimizda');
await b.shot('docs/screenshots/final/about-refined-mobile.png',true);
await writeFile('docs/screenshots/final/extra-report.json',JSON.stringify(checks,null,2));
console.log(JSON.stringify(checks,null,2));b.close();
if(checks.some(c=>!c.passed))process.exitCode=1;
